### PR TITLE
Added modelComplex to handDetector.mpHands.Hands to fix Invoke 0.75

### PR DESCRIPTION
**Pull request by lduran2**
This is an attempt to fix issue <https://github.com/CIS3296SoftwareDesignF21/prj-03-gaming-with-gestures/issues/6>.

Please test before merging everyone!

### CODE REVIEW

**Review by ArchaePi — APPROVED** [review]
Looks great!

**Comment by lduran2** [comment]
Is this update necessary anymore? I ran `Modularfinger` with Anaconda, and it seems to be working fine now.

**Comment by lduran2** [comment]
`ModularFinger` uses `detectionCon = 1`, and I used it for `HandDirection` too. Is this okay or is it something to worry about?

**Review by tui84176 — COMMENTED** [review]
Nice work!

**Pull request merged**
